The Carpentries Workbench is designed to be modular with clear, cross-platform
system requirements. It will use the R programming language and [pandoc] under
the hood and will abide bhe the following rules:

1. Lesson contributors do not need to know anything about the toolchain to
   contribute in a meaningful way.
2. Elements of the toolchain that evaluates, validates, and stylizes lessons
   should live in separate repositories to allow for seamless updating.
3. The procedures should be well-documented and generalizable enough that the
   toolchain is not entirely dependent on R.

R is beneficial because it already has a mature ecosystem of packages for
publishing dynamic reports and web content from markdown, it works on all
platforms, and we teach it as part of our core curriculum.


:::::::::::::: callout

### Did everything work?

If everything worked, you should have seen a lot of output in your R console and
then your browser window open to reveal a page that looks identical to
https://carpentries.github.io/sandpaper-docs/.

If this did NOT work for you, please send any errors you encountered to Zhian at
zkamvar@carpentries.org or you can reach him on The Carpentries Slack. 

:::::::::::::::::::::::

The interface for The Carpentries Workbench is an R package called
[{sandpaper}](engine.html), which is designed to provide rapid updates to the
lessons on the fly. It uses a **two-step process for building lessons**:

1. render all modified source documents (e.g [RMarkdown][r-markdown] or plain
   Markdown) to [pandoc-flavored markdown][pandoc] to a staging folder called 
   `site/built/`.
2. combine metadata with the contents of `site/built/` and convert to HTML to
   the folder called `site/docs/`

![
Diagrammatic representation of the proposed toolchain (excluding GitHub). 
Lavender rectangles represent R packages, 
Plum rectangles represent interchangable tools, 
Powder Blue Ovals represent people.
](https://zkamvar.github.io/stunning-barnacle/img/broad-flow.dot.svg)

## Why make a new template?

New templates are nothing new for The Carpentries[^history] as we are forever
searching for a balance between using the tools we teach and scaling our
operations to accommodate the growing number of lessons we have in [The
Carpentries Incubator].

::::::::::::: discussion

### What can be improved?

The current template is a lesson template wrapped around a Jekyll blog. It has
all of the features we want, but it's showing its age in several ways:

1. By requiring four different languages to check and render the lesson,
   several people have turned to elaborate solutions to preview their lessons
   including [Using a GitHub fork](https://www.youtube.com/watch?v=0XoEdznJARc)
   and [Creating a Docker image](https://github.com/carpentries/lesson-docker/)
2. All of our R lessons use [RMarkdown][r-markdown] to combine code and prose
   into a document that renders the output automatically, which means any
   updates will get propogated. Because [Jekyll][jekyll] sites do not run R in
   the background, they cannot render these lessons, so a fifth language must
   be added on and pre-rendered before lessons are built.
3. Updating the lessons is no small feat. It relies on a trick that we use for
   people creating lessons by importing the carpentries repository (because the
   template button did not yet exist) so that we can create a new branch and 
   merge the current branch of the [styles repository][styles]. This creates a
   pull request with potentially hundreds of commits that you just have to
   trust works.
4. The configuration file contains a lot of information that the maintainer is
   explicitly expected to NOT change, which is the equivalent of 

::::::::::::::::::

The Carpentries Workbench is fresh start as we look back to our founding principles
and think about what is important for the lesson maintainer to focus on: the
lesson content. To achieve this, we have stripped away the styling elements and
present to you a template that contains two things you need to worry about:
content files written in plain markdown and one (1) flat configuration file. All
the styling templates and tooling have been cast off into their own repositories
so that these can be updated on the fly without needing to undergo a complex
pull requests. Moreover, the template will treat [RMarkdown][r-markdown]
documents as first-class citizens without any extra setup or commands.

The Carpentries Workbench is **not** designed to mimic aspects of the previous
template. This template is designed primarily for use in The Carpentries, but
should theoretically be extensible to other contexts. Most importantly,
**contributors should only be expected to know `markdown` and *very* minimal
`yaml` syntax.** in order to contribute to lessons.

Thus, there are a few rules that the new template should follow:

::::::::::::: checklist

### Template Rules

1. The main branch is the source of truth and should be protected
2. Accessibility is a priority for the lesson [based on the WCAG 2.1
   guidelines](https://www.w3.org/WAI/WCAG21/quickref/)
3. The style of the lessons should not live in the template
4. The only committed content should be content directly by the
   maintainer/contributor and configuration files
5. Episodes should not depend on the lesson template to be rendered
6. The generated lesson web page should exist as a stand-alone directory that
   can be shared offline

:::::::::::::::::::::


:::::::: callout

### Customization

One of the benefits of our [CC-BY 4.0][cc-by-human] template is that anyone can
take it and customize it for their own purposes. We have found such creative 
endeavors as using it as a [user guide for the Common Workflow Language](https://www.commonwl.org/user_guide/),
a [program-specific set of training materials](https://nbisweden.github.io/module-organising-data-dm-practices/),
and even [a lesson on cross-stitching](https://sgibson91.github.io/cross-stitch-carpentry/).

With the new tempalte, however, the customization would take place in a fork of
the [{varnish}] repository, where all of the styling elements live.

::::::::::::::

## Processing

The previous [Jekyll][jekyll] template used a single step to render markdown to
HTML, with the new template, we have a two step process that renders
[(R)Markdown][r-markdown] to markdown and then to HTML. Why use two steps? By
rendering in two steps, we do a couple of things:

1. Any format that can be rendred to markdown can potentially be a source
2. Markdown provides a much better diff than HTML, so diagnosing output issues
   on a lesson is eaiser. 
3. The resulting markdown can be used in other contexts without needing to
   rebuild. 

[The Carpentries Incubator]: https://carpentries.org/community-lessons/
[^history]: An incomplete history is noted in the 9.1.0 release: https://github.com/carpentries/styles/releases/tag/v9.1.0
