---
title: "Migrating from Jekyll"
teaching: 5 
exercises: 2
---

:::::::::::::::: questions :::::::::::::::::::::

- Who is responsible for migrating a lesson?
- What package should I use for migration?

::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::: objectives ::::::::::::::::::::

- Understand the challenges involved in migration
- Identify the shared components between the styles template and The Carpentries Workbench
- Identify the tool needed for migration

::::::::::::::::::::::::::::::::::::::::::::::::


## Quick Start

Got a lesson you want to convert? The [{pegboard}] package was built to do that!
The best way to do this is to **ask Zhian to do it for you** since this is a
process that should ideally only be done once. If you really want to, you can
also try for yourself:

1. Install the package using [the setup instructions](setup.html)
2. Open R
3. Run `pegboard::jekyll_to_sandpaper()` to transform your lesson.


::::::::::::::: callout

### :caution: THINGS MIGHT CHANGE :caution:

This feature is still in active development and may not yet work as advertised.

::::::::::::::::::::::::

## Challenges

In an ideal world, migration of a lesson would involve moving shared markdown
documents between folders, but unfortunately, this is not the case. The truth is
that there are [dozens of markdown
interpreters](https://github.com/markdown/markdown.github.com/wiki/Implementations)
that all have a complicated hierarchy of rules.

### A Question of Syntax

The styles template uses a markdown interpreter called [kramdown] because it
was the default interpreter for [Jekyll][jekyll] at the time. This syntax 
allowed us to create customized block quotes that served as waypoints in our
lessons to facilitate active learning. Unfortunately, the syntax diverged far 
enough from [GitHub Flavoured markdown (GFM)](https://github.github.com/gfm/)
that even if you were familiar with markdown, you would have to learn a new 
syntax to write your content.

Enter [pandoc]. This tool is a cross-platform document converter that [uses its
own flavor of markdown](https://pandoc.org/MANUAL#pandocs-markdown), that is
more closely related to GFM than [kramdown]. For example, all of the features
listed in the [extended syntax of the markdown guide](https://www.markdownguide.org/extended-syntax/)
are present in pandoc.

One of the biggest hurdles for the translation between [kramdown] and [pandoc]
syntax are two things: 

1. [Liquid templating syntax](https://shopify.github.io/liquid/basics/introduction/) (e.g. `{{ relative_root_path }}/{% link LICENSE.md %}` to link to the license
2. Trailing styles: https://github.com/swcarpentry/DEPRECATED-lesson-template/issues/279#issuecomment-115491610

To give a succint example, if I wanted to write this code block in markdown:

```python
import matplotlib
```

I would write

````markdown
```python
import matplotlib
```
````

However, [kramdown] specified this syntax:

````markdown
~~~
import matplotlib
~~~
{: .language-python}
````

While it was possible to use the GFM syntax in Kramdown, the first recommendation
from the documentation has always been to use the trailing styles, and so that
pattern stuck with the lessons. 

All this goes to show that switching between these two syntaxes is not a simple
task of find and replace.

### Folder structure

The folder structure of the Lesson has evolved sporadically based on need and 
entropy, which leaves us with "junk drawer" folders like "extras" that contain
materials for both the learners and instructors. Moreover, the old template had
separated the data folders from the episodes folders[^1]. On top of that, the 
lessons that use RMarkdown had episodes embedded in `_episodes_rmd/` where some
of the files in that folder were artifacts from previous runs.

### Questions, Objectives, and Keypoints

The yaml headers of lessons contained bullet points for the questions, objectives,
and keypoints, but it became difficult to write markdown in yaml quotation marks,
so we have decided to migrate them to blocks in the lesson document itself.

### Block Quotes

Block quotes are convenient visual aids for writing callouts, but they are 
challenging to wrangle when you need to write code inside of them, especially
if you have nested content. Our solution to this is to use [fenced divs](https://zkamvar.github.io/glowing-chainsaw/05-fenced-div-challenge-blocks.html#example-1). 

## Solution

The migration of the lesson template is taken care of via [{pegboard}], which 
reads in the markdown source files using the commonmark markdown interpreter and
internally manipulates the kramdown syntax to something it can interpret.

The resulting markdown is then written to convert the following:

1. block quotes become fenced divs
2. code blocks are converted to standard markdown
3. liquid tags are converted to normal, reference-based links
4. non-metadata yaml items moved to the body of the document. 

::::::::::::::::::::::::::::: keypoints

 - Zhian will help migrate official lessons
 - use [{pegboard}] for migration

:::::::::::::::::::::::::::::::::::::::

[{pegboard}]: validator.html
[^1]: This was an explicit design choice to mimic how researchers should set up
    their analysis projects, but it lead to some confusion when it came to 
    rendering RMarkdown documents. 

<!-- Please do not delete anything below this line -->

```{r links, child = sandpaper::template_links()}
```
